# Generated by Django 4.2.16 on 2024-11-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aerobo_member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('nim', models.CharField(max_length=255)),
                ('divisi', models.CharField(max_length=255)),
                ('fakultas', models.CharField(max_length=255)),
                ('jurusan', models.CharField(max_length=255)),
                ('qr_code_aerobo', models.ImageField(blank=True, null=True, upload_to='qr_code_aerobo/')),
                ('last_in', models.JSONField(default=list)),
                ('screenshots', models.JSONField(default=list)),
            ],
        ),
    ]
