# Generated by Django 4.2.16 on 2024-11-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorlock_iot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aerobo_member',
            old_name='fakultas',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='aerobo_member',
            name='jurusan',
        ),
        migrations.AddField(
            model_name='aerobo_member',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
