# Generated by Django 4.2.16 on 2024-11-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorlock_iot', '0002_rename_fakultas_aerobo_member_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('no_identitas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah', models.PositiveIntegerField()),
                ('screenshot_barang', models.ImageField(blank=True, null=True, upload_to='screenshot_barang/')),
            ],
        ),
        migrations.RemoveField(
            model_name='aerobo_member',
            name='screenshots',
        ),
        migrations.AddField(
            model_name='aerobo_member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('jumlah_pinjam', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Diterima', 'Diterima'), ('Dikembalikan', 'Dikembalikan')], default='Diajukan', max_length=20)),
                ('aerobo_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorlock_iot.aerobo_member')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorlock_iot.barang')),
            ],
        ),
    ]
