# Generated by Django 4.2.16 on 2024-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorlock_iot', '0003_barang_remove_aerobo_member_screenshots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='divisi',
            field=models.CharField(choices=[('VTOL', 'VTOL'), ('RP', 'RP'), ('TD', 'TD'), ('Umum', 'Umum')], default='Umum', max_length=20),
        ),
        migrations.AddField(
            model_name='barang',
            name='status_kelayakan',
            field=models.BooleanField(default=True),
        ),
    ]
