# Generated by Django 4.2.16 on 2024-11-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorlock_iot', '0004_barang_divisi_barang_status_kelayakan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='status_kelayakan',
            field=models.CharField(choices=[('Rusak', 'Rusak'), ('Normal', 'Normal')], default='Normal', max_length=20),
        ),
    ]
